version: '3'

tasks:
  run:
    desc: "Run the project locally"
    cmds:
      - flutter run

  test:
    desc: "Run all tests"
    cmds:
      - flutter test

  load-deps:
    desc: "Load dependencies"
    cmds:
      - flutter pub get

  update-deps:
    desc: "Update dependencies"
    cmds:
      - flutter pub upgrade

  lint:
    desc: "Run linter"
    cmds:
      - flutter analyze

  fmt:
    desc: "Format code"
    cmds:
      - dart format .